config/routes.rb
P::Application.routes.draw do

  scope :api do
    get "/messages(.:format)" => "messages#index"
  end

  root "home#index"

  # resources :messages, only: [:index, :new, :show, :create, :destroy]

  devise_for :users, :path => 'accounts'

  resources :users do
    resources :messages
  end

# TODO: nest into users and then update path on the link
  resources :friendships

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  validate :cannot_add_self

  private

  def cannot_add_self
    binding.pry
    errors.add(:friend_id, 'You cannot add yourself as a friend.') if current_user.id == friend_id
  end

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :content
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages, dependent: :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # TODO: protect_from_forgery
  # http://technpol.wordpress.com/2013/09/21/angularjs-and-rails-csrf-protection/

  # protect_from_forgery with: :null_session

  before_action :authenticate_user!

  protect_from_forgery

  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end  


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  # GET / messages.json
  def index
    # maybe MessageS?.all
    render json: Message.all, root: "messages"
  end

  def new
  end

  def create
    @message = Message.new(message_params)
    @message.save
    render json: @message
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    render json: @message
  end


  private

  def message_params
    params.permit(:user_id, :content, :likes, :tags)
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div ng-controller="MessagesCtrl">

  <h4>Compose Message</h4>
  <form ng-submit="createMessage()">
    <input type="text" ng-model= "messageContents" placeholder="What's on your mind?"></input>
    <button type="submit"> Create Message </button>
  </form>

  <ul ng-repeat="message in messages">
    <li> {{message.messages.content}} <i ng-click="like()" class="fa fa-thumbs-o-up"></i> <i ng-click="deleteMessage()" class="fa fa-trash-o"></i> </li>

  </ul>
  <button ng-click="refresh()">Refresh</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- Setting the app Directive -->

<html ng-app="P">
<head>
  <title>P</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- font awesome -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Devise Start -->
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %>
  <!-- set current user id to window object -->
  <script type="text/javascript">
        var p = {};
        p.currentUserId = <%= current_user.id %>;
  </script>

<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<!-- Devise End -->

<header>P</header>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular-resource.min.js"></script>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

</body>
</html>

app/views/message/new.html.erb
  <%= form_for @message do |f| %>
    <%= f.label :message %>:
    <%= f.text_field :message %><br />

    <%= f.label :tags %>:
    <%= f.text_field :tags %><br />

    <%= f.submit %>
  <% end %>

app/views/users/index.html.erb
<% for user in @users %>
  <ul>
    <li> email is <%= user.email %></li> <%= button_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
  </ul>

<% end %>

app/views/users/show.html.erb
<h2>Following</h2>
<ul>
  <% for friendship in @user.friendships %>
    <li>
      <%=h friendship.friend.email %>
      (<%= button_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find People To Follow", users_path %></p>

<h2>Followers</h2>
<ul>
  <% for user in @user.inverse_friends %>
    <li><%=h user.email %></li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<h3>Please sign up</h3>

<p><%= current_user.email %></p>

<!-- Create A Message -->
<section>

  <h4>Compose Message</h4>
  <form>
    <input placeholder="What's on your mind?"></input>
    <button>Submit</button>
  </form>

</section>

<section>
  <p>News Feed Goes Here</p>
  <p><strong>Drew:</strong> Looking Forward to summer!</p>
  <p><strong>Paul:</strong> It </p>
</section>